# permissions for end users to edit neutronsriovagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neutronsriovagent-editor-role
rules:
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronsriovagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronsriovagents/status
  verbs:
  - get
