# permissions for end users to edit ovncontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovncontroller-editor-role
rules:
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovncontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovncontrollers/status
  verbs:
  - get
