# permissions for end users to view ovncontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovncontroller-viewer-role
rules:
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovncontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovncontrollers/status
  verbs:
  - get
