# permissions for end users to edit ovnmetadataagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovnmetadataagent-editor-role
rules:
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovnmetadataagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovnmetadataagents/status
  verbs:
  - get
