# permissions for end users to view ovsnodeosps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovsnodeosp-viewer-role
rules:
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovsnodeosps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovsnodeosps/status
  verbs:
  - get
