
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronsriovagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronsriovagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovncontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovncontrollers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovsnodeosps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - ovsnodeosps/status
  verbs:
  - get
  - patch
  - update
