apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ovnmetadataagents.neutron.openstack.org
spec:
  group: neutron.openstack.org
  names:
    kind: OVNMetadataAgent
    listKind: OVNMetadataAgentList
    plural: ovnmetadataagents
    singular: ovnmetadataagent
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: OVNMetadataAgent is the Schema for the ovnmetadataagents API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OVNMetadataAgentSpec defines the desired state of OVNMetadataAgent
            properties:
              commonConfigMap:
                description: name of configmap which holds general information on
                  the OSP env
                type: string
              ospSecrets:
                description: name of secret which holds sensitive information on the
                  OSP env
                type: string
              ovnMetadataAgentImage:
                description: container image to run for the daemon
                type: string
              roleName:
                description: Name of the worker role created for OSP computes
                type: string
              serviceAccount:
                description: service account used to create pods
                type: string
            required:
            - commonConfigMap
            - ospSecrets
            - ovnMetadataAgentImage
            - roleName
            - serviceAccount
            type: object
          status:
            description: OVNMetadataAgentStatus defines the observed state of OVNMetadataAgent
            properties:
              count:
                description: Count is the number of nodes the daemon is deployed to
                format: int32
                type: integer
              daemonsetHash:
                description: Daemonset hash used to detect changes
                type: string
            required:
            - count
            - daemonsetHash
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
